### ISSUE TITLE
Sample application / code that uses loopback-ds-tree-mixin

### ISSUE THREAD

**Issue by haresh333** [mbouclas/loopback-ds-tree-mixin#15]
Hi
Is there any sample applciation or code that showcases use of loopback-ds-tree-mixin?

regards

**Comment by mbouclas** [comment]
The only public example i have for you is [this](https://github.com/mbouclas/mcms-node-pages/blob/master/Services/Category/Helpers/find.js). I think that the documentation gives a good example of the available functionality though

**Comment by haresh333** [comment]
Thanks. I was able to use the mixin based on the documentation provided and it turned out to be easy and obvious.

Thanks for very good mixin.
